# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jBmJp5g2K_WhUmamqbR4jg_bdk4M1awD
"""

import csv
import random

# Listas de entrada
algoritmos = ['BubbleSort', 'InsertionSort', 'SelectionSort', 'QuickSort', 'MergeSort', 'HeapSort']
tamanhos = [10000, 50000, 100000, 300000, 800000, 1000000]
ordens = ['aleatoria', 'inversa']
tipos = ['Inteiro', 'Produto']

# Função para simular tempo
def gerar_tempo(alg, tamanho):
    if alg in ['BubbleSort', 'InsertionSort', 'SelectionSort']:
        base = tamanho ** 2 / 1e8  # crescimento quadrático
    else:
        base = tamanho * (random.uniform(1.0, 1.4) * (random.uniform(17, 22))) / 1e7  # crescimento log-linear
    return round(base * random.uniform(0.9, 1.2), 4)

# Criar lista de dados
dados = []
for alg in algoritmos:
    for tamanho in tamanhos:
        for ordem in ordens:
            for tipo in tipos:
                media = gerar_tempo(alg, tamanho)
                desvio = round(media * random.uniform(0.01, 0.05), 4)
                dados.append([alg, tamanho, ordem, tipo, media, desvio])

# Salvar CSV
with open("resultados_completos_simulados.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerow(["Algoritmo", "Tamanho", "Ordem", "Tipo", "Media(s)", "Desvio Padrao(s)"])
    writer.writerows(dados)